name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://admin:asswordp@192.168.43.22:8080/job/WebPy/build?token=remote-trigger-tocken-123"
          # curl -X POST "http://192.168.43.22:8080/job/WebPy/build?token=remote-trigger-tocken-123" \
          #--user "admin:asswordp"
